---
# =========================================================
# Prepare Ansible Controller
# =========================================================

- name: Prepare Ansible Controller
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    # -----------------------------------------------------
    # Install Docker Galaxy Role
    # -----------------------------------------------------

    - name: Install geerlingguy.docker Galaxy role
      ansible.builtin.command:
        cmd: ansible-galaxy role install geerlingguy.docker
      changed_when: false

    # -----------------------------------------------------
    # Install Docker Ansible Collection
    # -----------------------------------------------------

    - name: Install community.docker collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker
      changed_when: false


# =========================================================
# Configure Node1
# =========================================================

- name: Configure and deploy application to Node1
  hosts: webservers
  become: true
  gather_facts: true

  vars:
    image_tag: v1

  tasks:

    # -----------------------------------------------------
    # Install Docker using Galaxy role ,package and AWS CLI
    # -----------------------------------------------------

    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
        
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - unzip
        state: present
        update_cache: true
 
    - name: Check AWS CLI
      ansible.builtin.command:
        cmd: aws --version
      register: aws_cli_check
      failed_when: false
      changed_when: false

    - name: Install AWS CLI v2
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
          rm -rf /tmp/aws
          unzip -q /tmp/awscliv2.zip -d /tmp
          /tmp/aws/install
          rm -rf /tmp/aws /tmp/awscliv2.zip
      when: aws_cli_check.rc != 0


    # -----------------------------------------------------
    # Create ssm-user
    # -----------------------------------------------------

    - name: Ensure ssm-user exists
      ansible.builtin.user:
        name: ssm-user
        state: present
        create_home: true


    # -----------------------------------------------------
    # Add ssm-user to Docker group
    # -----------------------------------------------------

    - name: Add ssm-user to docker group
      ansible.builtin.user:
        name: ssm-user
        groups:
          - docker
        append: true


    # -----------------------------------------------------
    # Install Python Docker SDK
    # Required by community.docker modules
    # -----------------------------------------------------

    - name: Install Python Docker SDK
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: true


# -----------------------------------------------------
    # Login to Amazon ECR
    # -----------------------------------------------------

    - name: Login to Amazon ECR
      ansible.builtin.shell:
        cmd: |
          aws ecr get-login-password --region ap-southeast-1 |
          docker login \
            --username AWS \
            --password-stdin \
            990723917403.dkr.ecr.ap-southeast-1.amazonaws.com
      register: ecr_login
      changed_when: "'Login Succeeded' in ecr_login.stdout"


    # -----------------------------------------------------
    # Pull application image from ECR
    # -----------------------------------------------------

    - name: Pull application image
      community.docker.docker_image:
        name: "990723917403.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp-app:{{ image_tag }}"
        source: pull


    # -----------------------------------------------------
    # Remove previous application container
    # -----------------------------------------------------

    - name: Remove previous application container
      community.docker.docker_container:
        name: devops-app
        state: absent


    # -----------------------------------------------------
    # Start application container
    # -----------------------------------------------------

    - name: Start application container
      community.docker.docker_container:
        name: devops-app
        image: "990723917403.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp-app:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "80:80"