[webservers]
node1 ansible_host=10.0.0.5 ansible_aws_ssm_instance_id=i-021dde67d36a41f16

[ansible]
node2 ansible_host=10.0.0.135 ansible_aws_ssm_instance_id=i-0a93e5024716402e7

[monitoring]
node3 ansible_host=10.0.0.136 ansible_aws_ssm_instance_id=i-0f1a7986fd1678459

[nodes:children]
webservers
ansible
monitoring

[all:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-southeast-1
ansible_aws_ssm_bucket_name=devops-bootcamp-ansible-fareezizzudinothman