[webservers]
node1 ansible_host=10.0.0.5 ansible_aws_ssm_instance_id=i-084f4d58884e804d6

[monitoring]
node3 ansible_host=10.0.0.136 ansible_aws_ssm_instance_id=i-0aea6d26a2a3cf145

[all:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-southeast-1
ansible_aws_ssm_bucket_name=devops-bootcamp-ansible-fareezizzudinothman