[webservers]
node1 ansible_host=10.0.0.5 ansible_aws_ssm_instance_id=i-0ab559d1aeb9db9af

[ansible]
node2 ansible_host=10.0.0.135 ansible_aws_ssm_instance_id=i-0480869ff5347078d

[monitoring]
node3 ansible_host=10.0.0.136 ansible_aws_ssm_instance_id=i-0213a0f9e0c987a13

[nodes:children]
webservers
ansible
monitoring

[all:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-southeast-1
ansible_aws_ssm_bucket_name=devops-bootcamp-ansible-fareezizzudinothman