name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: devops-bootcamp-app

jobs:
#create PR
  test:
    name: Test Application
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run preflight tests
        run: npm test

      - name: Run unit tests
        run: npm run test:unit

      - name: Build application
        run: npm run build

#Merge PR
  build-and-push:
    name: Build and Push Docker Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest

    steps:

      # -----------------------------------------------------
      # Checkout source code
      # -----------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # Configure AWS using GitHub OIDC
      # -----------------------------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::990723917403:role/devops-github-actions-role
          aws-region: ${{ env.AWS_REGION }}


      # -----------------------------------------------------
      # Login to Amazon ECR
      # -----------------------------------------------------

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # -----------------------------------------------------
      # Set Docker image
      # -----------------------------------------------------

      - name: Set image URI
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "image=$REGISTRY/${ECR_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"


      # -----------------------------------------------------
      # Build Docker image
      # -----------------------------------------------------

      - name: Build Docker image
        run: |
          docker build \
            -t "${{ steps.image.outputs.image }}" \
            ./app


      # -----------------------------------------------------
      # Push Docker image to ECR
      # -----------------------------------------------------

      - name: Push Docker image
        run: |
          docker push "${{ steps.image.outputs.image }}"

      
      # -----------------------------------------------------
      # Trigger deployment on Node2 through AWS SSM + test2
      # -----------------------------------------------------

      - name: Deploy through Node2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-06ebb0259174573c5 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo -u ubuntu /home/ubuntu/devops-bootcamp-project/ansible/deploy.sh ${{ github.sha }}"]' \
            --region "${AWS_REGION}" \
            --query 'Command.CommandId' \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-06ebb0259174573c5 \
            --region "${AWS_REGION}"

          echo "========================================"
          echo "Deployment output"
          echo "========================================"

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-06ebb0259174573c5 \
            --region "${AWS_REGION}"